Ветка создание логики с друзьями и лайками.
Anna-Vashchenkova/java-filmorate pull request #6
Opened 2023-11-15 23:54 UTC by Anna-Vashchenkova

2023-11-16 05:51 UTC, avlin87 requested changes
Привет, Ань,
Хорошая работа,
смотри, пожалуйста, комментарии.

2023-11-16 05:51 UTC, avlin87 commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +@RestControllerAdvice
Отлично - отдельный класс для обработки ошибок.

2023-11-16 05:51 UTC, avlin87 commented on src/main/java/ru/yandex/practicum/filmorate/exception/NotFoundException.java
> +public class NotFoundException extends RuntimeException {
NotFoundException уже существует в библиотеке Java.
Лучше назвать DataNotFoundException или что-то подобное.

2023-11-16 05:51 UTC, avlin87 commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    public boolean equals(Object object) {
Давай нажмем Ctrl и кликнем на аннотацию `@Data`. Тогда мы должны увидель следующий текст в документации:
```
Generates getters for all fields, a useful toString method, and hashCode and equals implementations that check all non-transient fields. Will also generate setters for all non-final fields, as well as a constructor.
Equivalent to @Getter @Setter @RequiredArgsConstructor @ToString @EqualsAndHashCode.
```
В этом тексте сказано, что `@Data` генерирует, в том числе hashCode and equals.
Убедись, пожалуйста, нужно ли тебе реализовывать эти методы или достаточно `@Data`.

2023-11-16 05:51 UTC, avlin87 commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    public boolean equals(Object object) {
Убедись, пожалуйста, нужно ли тебе реализовывать эти методы или достаточно `@Data`.
Так же как и в Film классе.

2023-11-16 05:51 UTC, avlin87 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        } else {
В конце блока if будет return и код прекратит выполнение этого метода.
Мы можем обойтись без слова else.

2023-11-16 05:51 UTC, avlin87 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public Set<Film> getTop10Films() {
Сортировку можно выполнить с помощью stream - код будет более читаемый, а метод компактнее.
```
public Set<Film> getTop10Films() {
    return filmStorage.findAll().stream()
            .sorted(Comparator
                    .comparingInt(film -> film.getLikes().size())
                    .thenComparing(Film::getName))
            .limit(10)
            .collect(Collectors.toSet());
}
```

2023-11-16 05:51 UTC, avlin87 commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +        return films.stream().filter(film -> film.getId() == filmId).findFirst();
stream принято писать в несколько строк.
```
return films.stream()
                .filter(film -> film.getId() == filmId)
                .findFirst();
```
Легче читается и в случае ошибки проще понять, где случилась по номеру строки.

2023-11-16 19:56 UTC, Anna-Vashchenkova commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    public boolean equals(Object object) {
Переписала эти методы, так как иначе при изменении(обновлении) объекта они не сработают. А так только по ID сравнение

2023-11-16 20:02 UTC, Anna-Vashchenkova commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        } else {
пока не стала тут исправлять. Это исключение в ответах на запросы появлялось. Могу переделать условие ветвления и сначала исключение кинуть, а потом логику обновления.

2023-11-16 20:13 UTC, Anna-Vashchenkova commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public Set<Film> getTop10Films() {
Сначала стрим пыталась написать, film.getLikes().size() мне почему-то идея не дала составить вот так код, красным выделяла getLikes. И сейчас так же.

2023-11-16 20:23 UTC, Anna-Vashchenkova commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public Set<Film> getTop10Films() {
Не компилируется, не находит метод getLikes. Я его даже вручную прописала в классе фильм. Тут в стриме его не видно

2023-11-16 20:30 UTC, Anna-Vashchenkova commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public Set<Film> getTop10Films() {
![image](https://github.com/Anna-Vashchenkova/java-filmorate/assets/137414839/c801e0c0-4058-4aed-93ca-344252b4a23f)

2023-11-17 19:15 UTC, Anna-Vashchenkova commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public Set<Film> getTop10Films() {
Всё исправила, ошибку нашла.

2023-11-17 19:19 UTC, Anna-Vashchenkova commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    public boolean equals(Object object) {
Set будет работать не корректно, если не переопределять эти методы.

2023-11-18 17:41 UTC, avlin87 requested changes
Добавил комментарий по изменениям.

2023-11-18 17:41 UTC, avlin87 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public Collection<Film> getTop10Films(int count) {
Метод называется Top10Films а численное значение ты передаешь в метод. То есть от `10` метод никак не зависит. Переименуй, его, пожалуйста, в getTopFilms.

2023-11-18 17:41 UTC, avlin87 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public Collection<Film> getTop10Films(int count) {
Давай, пожалуйста, перестанем использовать Collection интерфейс совсем.
Если тебе не подходит `.collect(Collectors.toList());` преобразование в List, то поменяй на преобразование к интерфейсу, который тебе нужен.

2023-11-18 17:41 UTC, avlin87 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        /*Set<Film> all = filmStorage.findAll();
Закомментированный код лучше удалить.

2023-11-18 20:56 UTC, Anna-Vashchenkova commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public Collection<Film> getTop10Films(int count) {
Исправила.

2023-11-18 20:56 UTC, Anna-Vashchenkova commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public Collection<Film> getTop10Films(int count) {
Исправила.

2023-11-18 20:56 UTC, Anna-Vashchenkova commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        /*Set<Film> all = filmStorage.findAll();
Удалила.

2023-11-19 19:14 UTC, avlin87 approved these changes
Хорошо, работу принимаю.

2023-12-09 11:42 UTC, merged